-- MySQL Script generated by MySQL Workbench
-- Thu Nov 16 14:13:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cqf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cqf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cqf` DEFAULT CHARACTER SET utf8 ;
USE `cqf` ;

-- -----------------------------------------------------
-- Table `cqf`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`cidade` (
  `idcidade` INT NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `cep` INT(8) NOT NULL,
  `cidade_idcidade` INT NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NULL,
  `complemento` VARCHAR(45) NULL,
  `pontoReferencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idendereco`),
  FOREIGN KEY (`cidade_idcidade`)REFERENCES `cqf`.`cidade` (`idcidade`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `senha` VARCHAR(8) NOT NULL,
  `cpf` INT(11) NOT NULL UNIQUE,
  `telefone` INT(11) NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `cqf`.`endereco` (`idendereco`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`reclamacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`reclamacao` (
  `idreclamacao` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `data_reclamacao` DATE NOT NULL,
  `status` INT NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idreclamacao`),
  FOREIGN KEY (`categorias_idcategorias`) REFERENCES `cqf`.`categorias` (`idcategorias`),
  FOREIGN KEY (`endereco_idendereco`) REFERENCES `cqf`.`endereco` (`idendereco`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`anexos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`anexos` (
  `idanexos` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NULL,
  `reclamacao_idreclamacao` INT NOT NULL,
  PRIMARY KEY (`idanexos`),
  FOREIGN KEY (`reclamacao_idreclamacao`) REFERENCES `cqf`.`reclamacao` (`idreclamacao`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`prefeitura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`prefeitura` (
  `idprefeitura` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL UNIQUE,
  `senha` VARCHAR(8) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idprefeitura`),
  FOREIGN KEY (`endereco_idendereco`) REFERENCES `cqf`.`endereco` (`idendereco`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`prefeitura_has_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`prefeitura_has_categorias` (
  `prefeitura_idprefeitura` INT NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  PRIMARY KEY (`prefeitura_idprefeitura`, `categorias_idcategorias`),
  FOREIGN KEY (`prefeitura_idprefeitura`) REFERENCES `cqf`.`prefeitura` (`idprefeitura`),
  FOREIGN KEY (`categorias_idcategorias`) REFERENCES `cqf`.`categorias` (`idcategorias`)
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
