-- MySQL Script generated by MySQL Workbench
-- Fri Nov 17 13:13:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cqf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cqf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cqf` DEFAULT CHARACTER SET utf8 ;
USE `cqf` ;

-- -----------------------------------------------------
-- Table `cqf`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`cidade` (
  `idcidade` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idcidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`endereco` (
  `idendereco` INT NOT NULL,
  `cep` INT(8) NOT NULL,
  `cidade_idcidade` INT NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NULL,
  `complemento` VARCHAR(45) NULL,
  `pontoReferencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idendereco`),
  FOREIGN KEY (`cidade_idcidade`) REFERENCES `cqf`.`cidade` (`idcidade`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cqf`.`anexos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`anexos` (
  `idanexos` INT NOT NULL,
  `url` VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (`idanexos`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cqf`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `senha` VARCHAR(8) NOT NULL,
  `cpf` INT(11) NOT NULL UNIQUE,
  `telefone` INT(11) NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  `imagem_perfil` INT NULL,
  PRIMARY KEY (`idusuario`),
  FOREIGN KEY (`endereco_idendereco`) REFERENCES `cqf`.`endereco` (`idendereco`),
  FOREIGN KEY (`imagem_perfil`) REFERENCES `cqf`.`anexos` (`idanexos`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`categorias` (
  `idcategorias` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`reclamacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`reclamacao` (
  `idreclamacao` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `data_reclamacao` DATE NOT NULL,
  `status` INT NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idreclamacao`),
  FOREIGN KEY (`categorias_idcategorias`) REFERENCES `cqf`.`categorias` (`idcategorias`),
  FOREIGN KEY (`endereco_idendereco`) REFERENCES `cqf`.`endereco` (`idendereco`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`departamento` (
  `iddepartamento` INT NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL UNIQUE,
  `senha` VARCHAR(8) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  `logo` INT NOT NULL,
  PRIMARY KEY (`iddepartamento`),
  FOREIGN KEY (`endereco_idendereco`) REFERENCES `cqf`.`endereco` (`idendereco`),
  FOREIGN KEY (`logo`) REFERENCES `cqf`.`anexos` (`idanexos`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cqf`.`categorias_departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`categorias_departamento` (
  `prefeitura_idprefeitura` INT NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  FOREIGN KEY (`prefeitura_idprefeitura`) REFERENCES `cqf`.`departamento` (`iddepartamento`),
  FOREIGN KEY (`categorias_idcategorias`) REFERENCES `cqf`.`categorias` (`idcategorias`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`likes` (
  `usuario_idusuario` INT NOT NULL,
  `reclamacao_idreclamacao` INT NOT NULL,
  FOREIGN KEY (`usuario_idusuario`) REFERENCES `cqf`.`usuario` (`idusuario`),
  FOREIGN KEY (`reclamacao_idreclamacao`) REFERENCES `cqf`.`reclamacao` (`idreclamacao`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cqf`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`favoritos` (
  `usuario_idusuario` INT NOT NULL,
  `reclamacao_idreclamacao` INT NOT NULL,
  FOREIGN KEY (`usuario_idusuario`) REFERENCES `cqf`.`usuario` (`idusuario`),
  FOREIGN KEY (`reclamacao_idreclamacao`) REFERENCES `cqf`.`reclamacao` (`idreclamacao`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`area_atuacao_departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`area_atuacao_departamento` (
  `cidade_idcidade` INT NOT NULL,
  `prefeitura_idprefeitura` INT NOT NULL,
  FOREIGN KEY (`cidade_idcidade`) REFERENCES `cqf`.`cidade` (`idcidade`),
  FOREIGN KEY (`prefeitura_idprefeitura`) REFERENCES `cqf`.`departamento` (`iddepartamento`)
)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `cqf`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`comentario` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `comentario` TEXT(200) NULL,
  `usuario_idusuario` INT NOT NULL,
  `reclamacao_idreclamacao` INT NOT NULL,
  PRIMARY KEY (`idcomentario`),
  FOREIGN KEY (`usuario_idusuario`) REFERENCES `cqf`.`usuario` (`idusuario`),
  FOREIGN KEY (`reclamacao_idreclamacao`) REFERENCES `cqf`.`reclamacao` (`idreclamacao`)
)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `cqf`.`reclamacao_has_anexos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`reclamacao_has_anexos` (
  `reclamacao_idreclamacao` INT NOT NULL,
  `anexos_idanexos` INT NOT NULL,
  FOREIGN KEY (`reclamacao_idreclamacao`) REFERENCES `cqf`.`reclamacao` (`idreclamacao`),
  FOREIGN KEY (`anexos_idanexos`) REFERENCES `cqf`.`anexos` (`idanexos`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cqf`.`atualizacoes_reclamacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cqf`.`atualizacoes_reclamacoes` (
  `idatualizacoes_reclamacoes` INT NOT NULL,
  `descricao` TEXT(200) NOT NULL,
  `prazo` DATE NOT NULL,
  `data_atualizacao` DATE NOT NULL,
  `reclamacao_idreclamacao` INT NOT NULL,
  PRIMARY KEY (`idatualizacoes_reclamacoes`),
  FOREIGN KEY (`reclamacao_idreclamacao`) REFERENCES `cqf`.`reclamacao` (`idreclamacao`)
)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
